### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by gamedevgs** [orndorffgrant/bnhook#7]
Hello.  i instal from gui plugin. then have a error
```Failed to import python plugin: community/jeffli678_bnhook: No module named filebytes.elf```
and  on terminal 
```pip install filebytes or pip3 install filebytes```
```Requirement already satisfied: filebytes in ./.local/lib/python3.8/site-packages (0.10.2)
ERROR: Could not find a version that satisfies the requirement or (from versions: none)
ERROR: No matching distribution found for or
```
After researching and installing I got an error like this. it happens in both windows and linux environments. I tried to find a fix but to no avail. hope you can help.

**Comment by orndorffgrant** [comment]
Hello @hoidq2525 Please post all issues to the new home of this plugin which is here: https://github.com/jeffli678/bnhook

I will archive this repo to make it clearer that this repo is no longer active.
